### ISSUE TITLE
Host without imagej cannot redefine viewers via SITK_SHOW_COMMAND

### ISSUE THREAD

**Issue by richardbeare** [SimpleITK/SimpleITK#602]
The SITK_SHOW_COMMAND allows redefinition of the viewer used by _Show_. However, _Show_ searches for imagej before doing anything else  https://github.com/SimpleITK/SimpleITK/blob/a4eba04b0380c3f76386d635a4c7defe92b2bb61/Code/IO/src/sitkShow.cxx#L616

_FindImageJ_ issues an exception if it can't find imagej:  https://github.com/SimpleITK/SimpleITK/blob/a4eba04b0380c3f76386d635a4c7defe92b2bb61/Code/IO/src/sitkShow.cxx#L495

Thus, if there's no imagej on a host, supplying an environment variable doesn't help because the exception bypasses the environment variable code.

```r
library(SimpleITK)
m <- ReadImage("/usr/share/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz")
Show(m)
Error in f(...) : Exception in SITK - check warnings
In addition: Warning message:
In f(...) :
  Exception thrown in SimpleITK Show: /home/richardb/Projects/ITK4/SimpleITK/Code/IO/src/sitkShow.cxx:495:
sitk::ERROR: No appropriate executable found.

```

```bash
mkdir /tmp/bin
# pretend imagej is installed
touch /tmp/bin/imagej
export PATH=${PATH}:/tmp/bin
export SITK_SHOW_COMMAND=$(which itksnap)
```
```r
library(SimpleITK)
m <- ReadImage("/usr/share/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz")
Show(m)
# Success
```

**Comment by dave3d** [comment]
I've submitted a patch that should fix the problem.

https://github.com/SimpleITK/SimpleITK/pull/604

**Comment by blowekamp** [comment]
@Dave You can reference an issue in a pull request and indicates that it "fixed issues ###" and GitHub will automatically link and close the issue when merged. Here is the docs:
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by rojinsafavi** [comment]
I am having the same issue

I ran following code from your examples:

`python ImageRegistrationMethod1.py ~/Downloads/chrome_dl/k/C2-Composite0.tif ~/Downloads/chrome_dl/k/C2-Composite1.tif trial.hdf5`

and I got:

`Optimizer stop condition: RegularStepGradientDescentOptimizerv4: Step too small after 18 iterations. Current step (0.0078125) is less than minimum step (0.01).
 Iteration: 19
 Metric value: 24522.5579727
Traceback (most recent call last):
  File "ImageRegistrationMethod1.py", line 71, in <module>
    sitk.Show( cimg, "ImageRegistration1 Composition" )
  File "/Users/rojinsafavi/miniconda2/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 7887, in Show
    return _SimpleITK.Show(*args, **kwargs)
RuntimeError: Exception thrown in SimpleITK Show: /scratch/dashboard/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK/Code/IO/src/sitkShow.cxx:495:
sitk::ERROR: No appropriate executable found.`

**Comment by blowekamp** [comment]
Have you installed Fiji?

This issue is closed. While similar it looks like you have a separate problem, please create a new issue if installing Fiji does not resolve the problem.

**Comment by blowekamp** [comment]
closed by #604
